version: '3.2'

services:
  postgres:
    image: postgres:11-alpine
    container_name: nasdaqdata-postgres
    volumes:
      - ./configs/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=nasdaqdata
      - POSTGRES_USER=nasdaqdata
      - POSTGRES_PASSWORD=nasdaqdata
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432

volumes:
  postgres_data: